### ISSUE TITLE
Accoustic impedance matching in unit-cells of different in-plane dimensions. 

### ISSUE THREAD

**Issue by AvonReppert** [dschick/udkm1DsimML#6]
The strain simulation of the udkm 1D-sim toolbox allows for the strain wave calculation in multilayer heterostructures. However the applications in the examples often assumes perovskite sample structures with nearly identical unit-cell dimensions of all sample constituents. 

A simulation of a typical sample structure such as Au (111 0.407/sqrt(3) lattic plane spacing)/Ni(100 with 0.352 nm lattice constant)/MgO (0.421 nm ) lattice constant however have a very different masses per unit cell since the in plane dimensions of the unit cells vary. The accoustic impedance Z = density * sound velocity is then calculated wrongly which leads to unrealistic strain reflections at the interfaces. 
Changing the mass of the unit cell so that it is normalized to the 1 square Angström here shown for the example of FePt example solves this issue in the strain simulation:

` FePt.mass = FePt.mass / FePt.aAxis/ FePt.bAxis * (1*u.ang)^2;

FePt.aAxis = 1*u.ang; FePt.bAxis = 1*u.ang;

FePt.area =  FePt.aAxis * FePt.bAxis; 

FePt.volume = FePt.cAxis * FePt.area;

FePt.soundVel = svFePt; % one needs to redefine sound velocity here since it adapts the spring constant to the modified unit cell mass `

However this definition of the unit has now too many atoms per unit area so that the subsequent X-ray simulations turn out to be wrong. One can use the strain simulation but before running the X-ray simulation one needs to reset the unit cell to original dimensions otherwise the X-Ray intensities turn out wrong. 

This could be done for each strain simulation and automatically reverted for each X-ray simulation from my point of view so that the toolbox is also giving correct results for not epitaxially matched films. 

This creates problems as the mass density per area is strongly different and one needs to take an uni

**Comment by dschick** [comment]
please check that also with the latest version available on github.

in the unitCell.m in line 408-410 in the addAtom method:
```
obj.density     = obj.mass / obj.volume;
obj.mass        = obj.mass * 1*units.ang^2 / obj.area;
obj.calcSpringConst();
```
the mass is already normalized to 1Ang^2 because of exactly whould you described above.
However the density and area of the uniCell is unchanged in order to not make further mistakes e.g. in the X-ray diffraction which is also normalized by the unitCell area.

**Comment by AleksUDKM** [comment]
Ok great I did not know that this issue from a previous version was fixed
Thanks

**Comment by AvonReppert** [comment]
Ok great I did not know that this issue from a previous version was fixed
Thanks
